export const TEXT = {
  common: {
    home: "홈",
    close: "닫기",
    cancel: "취소",
    save: "저장",
    delete: "삭제",
    create: "등록",
    edit: "수정",
    upload: "업로드",
    download: "다운로드",
    search: "검색",
    settings: "설정",
    logout: "로그아웃",
    myProfile: "내 정보",
    changePassword: "비밀번호 변경",
    loading: "불러오는 중...",
    noData: "등록된 데이터가 없습니다.",
    noResults: "조회된 내역이 없습니다.",
    accessDenied: "접근 권한이 없습니다.",
    pageLoadFailed: "페이지를 불러오지 못했습니다.",
    goToDashboard: "대시보드로 이동",
    closeToast: "닫기",
  },
  roles: {
    super_admin: "슈퍼관리자",
    hq_admin: "본사 교육관리자",
    instructor: "강사",
    employee: "직원",
    headquarters: "본사",
  },
  routes: {
    dashboard: "대시보드",
    myTrainings: "내 교육",
    myHistory: "교육 이력",
    trainings: "교육 관리",
    trainingDetail: "교육 상세",
    historyCards: "직원 교육 이력카드",
    historyOverview: "교육 관리",
    materials: "교육자료",
    employees: "직원관리대장",
    employeeDetail: "직원 상세",
    statistics: "통계",
    announcements: "공지사항",
    templates: "교육 템플릿",
    notificationSettings: "알림 설정",
    slideshow: "슬라이드쇼",
    lessonPlan: "교안 작성",
    companies: "회사 관리",
    branches: "지점 관리",
    accounts: "계정 관리",
    adminEmployees: "직원 관리",
    adminSettings: "시스템 설정",
    instructorTrainings: "교육 관리",
  },
  nav: {
    groups: {
      system: "시스템 관리",
      operations: "교육 운영",
      people: "직원 관리",
      communication: "커뮤니케이션",
      teaching: "강의 운영",
      info: "안내",
      learning: "교육",
    },
    notifications: "알림 설정",
    assignedTrainings: "배정 교육",
  },
  brand: {
    serviceName: "TAS Education Lab",
    platformName: "TAS Education Lab v1.0",
    loginTagline: "사내 교육 운영과 이력 관리를 위한 통합 플랫폼",
    loginFooter: "TAS Education Lab",
    shortName: "TAS Lab",
  },
  topbar: {
    profileMetaSeparator: " / ",
    titleSuffix: "TAS Education Lab",
    logoutFailed: "로그아웃 중 오류가 발생했습니다.",
  },
  notifications: {
    title: "알림",
    markAllRead: "모두 읽음",
    empty: "새로운 알림이 없습니다.",
    overduePrefix: "[기한초과]",
    overdueMessage: (title) => `${title} 교육의 수료기한이 지났습니다.`,
    expiringPrefix: "[마감임박]",
    expiringMessage: (title, days) => `${title} 교육 마감까지 ${days}일 남았습니다.`,
    overdueBanner: (count) => `기한이 지난 교육이 ${count}건 있습니다.`,
    expiringBanner: (count) => `마감이 임박한 교육이 ${count}건 있습니다.`,
  },
  employeeAdmin: {
    title: "직원 관리",
    subtitle: "직원 계정을 생성하고, 엑셀 일괄 업로드 및 삭제를 관리합니다.",
    downloadTemplate: "양식 다운로드",
    excelUpload: "Excel 업로드",
    stats: {
      employees: "전체 직원",
      active: "활성 직원",
      branches: "등록 지점",
    },
    allBranches: "전체 지점",
    searchPlaceholder: "이름, 사번, 지점으로 검색",
    emptyTitle: "등록된 직원이 없습니다.",
    emptyDescription: "Excel 업로드로 직원 계정을 일괄 등록해 주세요.",
    table: {
      empNo: "사번",
      name: "이름",
      branch: "지점",
      position: "직급",
      login: "로그인 계정",
      status: "상태",
      createdAt: "등록일",
    },
    status: {
      active: "활성",
      inactive: "비활성",
    },
    uploadModal: {
      title: "직원 Excel 업로드",
      defaultBranch: "기본 지점",
      defaultBranchHint: "행의 지점 값이 비어 있으면 여기서 선택한 지점으로 등록됩니다.",
      useFileBranch: "엑셀 지점값 우선 사용",
      file: "Excel 파일",
      fileHint: "필수 컬럼: 사번, 이름, 지점, 직급. 초기 비밀번호는 사번과 동일하게 생성됩니다.",
      example: "예시 컬럼: 사번 / 이름 / 지점 / 직급",
      branchExample: "지점 값은 PUS, TAE, ICN, CJU 같은 코드 또는 지점명으로 입력할 수 있습니다.",
      previewIdle: "파일을 선택하면 업로드 전 검증 결과와 미리보기가 표시됩니다.",
      action: "직원 일괄 생성",
      noFile: "먼저 업로드할 Excel 파일을 선택해 주세요.",
      parseFailed: "Excel 파일을 읽는 중 오류가 발생했습니다.",
      parseFailedDetail: "선택한 파일을 해석할 수 없습니다. 파일 형식과 컬럼명을 확인해 주세요.",
      previewTitle: "업로드 미리보기",
      validSummary: (valid, invalid) => `정상 ${valid}건 / 오류 ${invalid}건`,
      validationPassed: "검증이 완료되었습니다. 업로드 시 Authentication 계정과 Realtime Database 프로필이 함께 생성됩니다.",
      previewOnly: "미리보기에는 처음 20건만 표시됩니다.",
      row: "행",
      ready: "등록 가능",
      error: "오류",
      resultTitle: "업로드 결과",
      created: "생성",
      skipped: "건너뜀",
      failed: "실패",
      loginFormat: "로그인 계정 형식",
      initialPassword: "초기 비밀번호",
      createdEmployees: "생성된 직원",
      skippedEmployees: "건너뛴 직원",
      failedEmployees: "실패한 직원",
      done: "완료",
      createSuccess: (created, skipped) => `직원 ${created}건을 생성했고 ${skipped}건은 건너뛰었습니다.`,
      createFailed: "직원 생성 중 오류가 발생했습니다.",
      invalidRows: "오류가 있는 행이 있어 업로드를 진행할 수 없습니다.",
      missingEmpNo: "사번이 비어 있습니다.",
      missingName: "이름이 비어 있습니다.",
      branchNotMatched: "지점을 찾을 수 없습니다. 지점 코드 또는 지점명을 확인해 주세요.",
    },
    deleteModal: {
      title: "직원 삭제",
      description: (name) => `${name} 직원을 삭제하시겠습니까?<br/>Authentication 계정과 Realtime Database 프로필이 함께 삭제됩니다.`,
      success: "직원 계정이 삭제되었습니다.",
      failed: "직원 삭제 중 오류가 발생했습니다.",
    },
    branchLabelSeparator: " - ",
  },
};
